# Artificial Neural Network

### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.16.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, : -1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
y_train = y_train.reshape(len(y_train),1)

In [7]:
y_test = y_test.reshape(len(y_test),1)

### Feature Sacling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc2 = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
y_train = sc2.fit_transform(y_train)
y_test = sc2.transform(y_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam' , loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100

240/240 [==============================] - 27s 2ms/step - loss: 0.6528
Epoch 2/100
240/240 [==============================] - 1s 2ms/step - loss: 0.2936
Epoch 3/100
240/240 [==============================] - 1s 3ms/step - loss: 0.2017
Epoch 4/100
240/240 [==============================] - 1s 3ms/step - loss: 0.1559
Epoch 5/100
240/240 [==============================] - 1s 3ms/step - loss: 0.1287
Epoch 6/100
240/240 [==============================] - 1s 3ms/step - loss: 0.1102
Epoch 7/100
240/240 [==============================] - 1s 3ms/step - loss: 0.0976
Epoch 8/100
240/240 [==============================] - 1s 3ms/step - loss: 0.0874
Epoch 9/100
240/240 [==============================] - 1s 2ms/step - loss: 0.0801
Epoch 10/100
240/240 [==============================] - 1s 3ms/step - loss: 0.0743
Epoch 11/100
240/240 [==============================] - 1s 3ms/step - loss: 0.0706
Epoch 12/100
240/240 [==============================] - 1s 3ms/step - loss: 0.0677
Epoch 13/10

### Predicting the results of the Test set

In [21]:
y_pred = ann.predict(X_test)

60/60 [==============================] - 0s 2ms/step


In [24]:
sc2.inverse_transform(y_pred)

array([[456.88345],
       [438.64728],
       [434.02847],
       ...,
       [483.38605],
       [435.1073 ],
       [456.40646]], dtype=float32)

In [25]:
np.set_printoptions = 2
print(np.concatenate((sc2.inverse_transform(y_pred.reshape(len(y_pred),1)), sc2.inverse_transform(y_test.reshape(len(y_test),1))),1))

[[456.88345337 455.27      ]
 [438.64727783 436.31      ]
 [434.0284729  440.68      ]
 ...
 [483.38604736 479.53      ]
 [435.1072998  435.76      ]
 [456.40646362 457.1       ]]


## Printing the accuracy

In [26]:
from sklearn.metrics import r2_score
print(r2_score(sc2.inverse_transform(y_pred),sc2.inverse_transform(y_test)))

0.9396155479406542
